services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:slim
    container_name: open-webui
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - ./data:/app/backend/data
    env_file:
      - .env
    environment:
      WEBUI_URL: https://ai.abhithube.com
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OPENID_PROVIDER_URL: https://auth.abhithube.com/.well-known/openid-configuration
      OAUTH_PROVIDER_NAME: "Pocket ID"
      OPENID_REDIRECT_URI: https://ai.abhithube.com/oauth/oidc/callback

networks:
  athena:
    external: true 
