services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket-id
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - ./data:/app/data
    environment:
      - APP_URL=https://auth.abhithube.com

networks:
  athena:
    external: true 