services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - ./data:/data/
    environment:
      DOMAIN: https://vault.abhithube.com
      SIGNUPS_ALLOWED: false

networks:
  athena:
    external: true 