services:
  grist:
    image: gristlabs/grist-oss
    container_name: grist
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - /opt/athena/grist:/persist
    env_file:
      - .env
    environment:
      APP_HOME_URL: https://spreadsheet.abhithube.com
      GRIST_OIDC_IDP_ISSUER: https://auth.abhithube.com/.well-known/openid-configuration

networks:
  athena:
    external: true 