services:
  memos:
    image: neosmemo/memos
    container_name: memos
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - /opt/athena/memos:/var/opt/memos

networks:
  athena:
    external: true 