services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    networks:
      - athena
    volumes:
      - ./data:/beszel_data
      - ./socket:/beszel_socket
    environment:
      USER_CREATION: true
      DISABLE_PASSWORD_AUTH: true

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./agent:/var/lib/beszel-agent
      - ./socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://status.abhithube.com

networks:
  athena:
    external: true 